version: "3"
services:
   chamber:
      build: chamber
      volumes:
         - ./chamber:/tmp/
   
   telegrafinput:
      image: "telegraf:1.22.4"
      volumes: 
         - ./data/telegrafinput/telegraf.conf:/etc/telegraf/telegraf.conf
         - ./data/chamber:/tmp/chamber
   
